language: rust

rust:
  - stable
  - beta
  - nightly

  # For clippy.
  - nightly-2017-12-28

env:
  global:
    - CLIPPY_VERSION=0.0.177

before_script:
  - ./travis-script before_script

script:
  - ./travis-script script
  - cargo build --verbose --all --all-targets
  - cargo test --verbose --all
  - cargo build --release --verbose --all --all-targets
  - cargo test --release --verbose --all

os:
  - linux
  - osx
